### ISSUE TITLE
Key for cluster component should also contains clusters zoom level - cluster_id is not unique across different zoom levels

### ISSUE THREAD

**Issue by lpikora** [novalabio/react-native-maps-super-cluster#38] opened 2018-06-11 00:58 UTC
I think that `cluster_id` property is unique only for clusters on the same zoom level. On different zoom level, cluster_id cane be same for some cluster. This could cause rendering issues in RN maps plugin.

For fix this I suggest add new zoom property with region zoom to each cluster here after get data from getClusters() eg.:

```
data = this.getClusters(region)
data.forEach((item) => {
  item.zoom = region.zoom;
})
 this.setState({ region, data })
```

https://github.com/novalabio/react-native-maps-super-cluster/blob/e0f3593702b69d63be4f29816aaf04dbc046344b/ClusteredMapView.js#L87

And then add zoom level to key property of clusters marker eg.:

```
key={`cluster-${d.zoom}-${d.properties.cluster_id}`}
```

https://github.com/novalabio/react-native-maps-super-cluster/blob/e0f3593702b69d63be4f29816aaf04dbc046344b/ClusteredMapView.js#L139

This can fix some rendering issues on Android.

**Comment by ttencate** [comment] 2018-06-12 17:48
I can confirm that this fixed #34 for me. However, the suggested fix needs to be applied inside `getClusters`, because this is called from two locations.

But here's a strange thing. This was fixed in SuperCluster in https://github.com/mapbox/supercluster/pull/58, which rolls the `zoom` into the `cluster_id`. This change is present in v3.0.0 and up. `react-native-maps-super-cluster` is using v3.0.2, so this workaround shouldn't even be necessary!

Am I missing something?

**Comment by 39otrebla** [comment] 2018-06-16 18:27
@lpikora @ttencate  thanks for the contribution. We'll look asap into mapbox's supercluster, would be better to use their `zoom` stuff if possibile. Then, based on the previous outcome, we'll schedule an update for fixing the rendering issue.

**Comment by atothewest** [comment] 2018-06-20 09:32
FWIW I don't think `Region` has a `zoom` property in RN Maps, see: https://github.com/react-community/react-native-maps/blob/master/docs/mapview.md#types

So `region.zoom` in this fix will be returning `undefined`.

A zoom value can be approximated with this statement:

`const zoom = Math.round(Math.log(360 / region.longitudeDelta) / Math.LN2)`

(Or remove the `Math.round` wrapping for a float value that might be better suited for unique keys in some scenarios)

**Comment by ttencate** [comment] 2018-06-20 13:32
Yeah, maybe I was too quick with my conclusion. In my actual attempt I also discovered that `zoom` was not available, and I substituted `Math.random()` instead. While this fixed the problem and points towards a solution being related to the `key` property, it is obviously not a good solution and doesn't conclusively prove that a lack of `zoom` is the root cause of the issue.

**Comment by leolusoli** [comment] 2018-07-02 13:54
`Math.random()` instead of zoom calculation doesn't solve the problem

**Comment by DanGDroid** [comment] 2018-07-09 13:05
found this [issue](https://github.com/react-community/react-native-maps/issues/1870#issuecomment-370601097) relevant and solved my problem

**Comment by leolusoli** [comment] 2018-07-18 11:50
Attach the zoom level to the cluster key is a good thing for makes map render lifecycle more consistent. Anyways, it will not solve the custom marker issue on Android

Based on @DanGDroid post, seem that is another RN Map bug.

Closing.

**Closed by leolusoli** 2018-07-18 11:50 UTC
