### ISSUE TITLE
Custom Marker Rendering Issues

### ISSUE THREAD

**Issue by djpetenice** [novalabio/react-native-maps-super-cluster#34] opened 2018-05-01 12:59 UTC
OS: Android

There definitely seems to be issues with custom markers. Clusters are rendering intermittently when zooming and panning. Been playing with the radius and extent props but nothing seems to resolve it. 

Any ideas?

**Comment by DanGDroid** [comment] 2018-05-01 13:14
same here #19 , couldn't fix yet

**Comment by ttencate** [comment] 2018-05-12 14:45
Same here. Individual markers are also rendered intermittently. Sometimes by zooming in and out onto the same area a couple of times, making clusters repeatedly group and ungroup, I can make almost all markers and clusters disappear.

**Comment by 39otrebla** [comment] 2018-05-19 11:07
@djpetenice we are looking into this, we'll post the outcome asap. Could you please provide a code sample of your use case? Are you making intense usage of `setState()` in your parent Component?

**Comment by Biromain** [comment] 2018-05-22 07:31
No intense usage of `setState()`.
Only use state for keyboard open/close, selected marker and when map is ready.
All by props with redux and reselect.

Markers appear/disappear only when i'm zooming in and out on Android.

**Comment by otaviogaiao** [comment] 2018-06-05 20:29
I'm having some trouble too. I'm running on iOS. Scrolling is very buggy, sometimes it wont scroll, so I have to try again, if I have two clusters very close, sometimes they render as just one, other times separately. I also keep getting the following warning: Failed prop type: The prop `coordinate.latitude` is marked as required in `MapMarker`, but its value is undefined.

I don't know if I'm doing something wrong or if its a bug. My code is here:

```

constructor(props) {
    super(props);

    this.abrirSolicitacao = this.abrirSolicitacao.bind(this);
    this.setMyLocation = this.setMyLocation.bind(this);
    this.onRegionChange = this.onRegionChange.bind(this);
    this.map = null;
  }

  state = {
    erro: false,
    hasPermission: true,
    region: {
      latitude: -16.686898,
      longitude: -49.264811,
      latitudeDelta: 0.0028162317524973446,
      longitudeDelta: 0.008046627782761107
    }
  };

  async componentDidMount() {
    if (Platform.OS === "android") {
      try {
        const granted = await PermissionsAndroid.request(
          PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION,
          {
            title: "Citsmart Field Service Location Permission",
            message: "Citsmart Field Service needs access to your location"
          }
        );
        this.setState({
          erro: false,
          hasPermission:
            granted === PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION
        });
      } catch (err) {
        this.setState({
          erro: true
        });
      }
    }
    this.setMyLocation();
  }

  abrirSolicitacao(requestId) {
    this.props.navigation.navigate("Solicitacao", { requestId });
  }

  async setMyLocation() {
    try {
      let position = await getCurrentLocation();
      this.setState({
        erro: false,
        hasPermission: true,
        region: {
          latitude: position.coords.latitude,
          longitude: position.coords.longitude,
          latitudeDelta: 0.018,
          longitudeDelta: 0.023
        }
      });
    } catch (err) {
      this.setState({
        erro: true
      });
    }
  }

  renderCluster = (cluster, onPress) => {
    const { pointCount, coordinate, clusterId } = cluster;

    // use pointCount to calculate cluster size scaling
    // and apply it to "style" prop below

    // eventually get clustered points by using
    // underlying SuperCluster instance
    // Methods ref: https://github.com/mapbox/supercluster
    const clusteringEngine = this.map.getClusteringEngine(),
      clusteredPoints = clusteringEngine.getLeaves(clusterId, 100);
    return (
      <Marker coordinate={coordinate} onPress={onPress}>
        <View style={styles.myClusterStyle}>
          <Text style={styles.myClusterTextStyle}>{pointCount}</Text>
        </View>
      </Marker>
    );
  };

  renderMarker = solicitacao => {
    return (
      <Marker
        coordinate={solicitacao}
        key={solicitacao.location.requestId.toString()}
        onPress={() => this.abrirSolicitacao(solicitacao.requestId)}
      />
    );
  };

  onRegionChange(region) {
    this.setState({ region });
  }

render() {
    const { region, hasPermission } = this.state;
    const { localizacoes } = this.props;

    return (
      <View style={styles.container}>
        {hasPermission ? (
          [
            <ClusteredMapView
              showsUserLocation
              style={styles.mapContainer}
              showsMyLocationButton={false}
              region={region}
              loadingEnabled
              data={localizacoes}
              renderMarker={this.renderMarker}
              renderCluster={this.renderCluster}
              onRegionChange={this.onRegionChange}
              key="mapa"
              ref={r => (this.map = r)}
            />,
            <View key="mensagem" style={styles.quantidadeMensagemContainer}>
              <Text>
                {strings("mapa.quantidade_solicitacoes", {
                  quantidade: localizacoes.length
                })}
              </Text>
            </View>,
            <FindMeButton
              containerStyle={styles.findMeButtonContainer}
              onPress={this.setMyLocation}
              key="findmebutton"
            />
          ]
        ) : (
          <View style={styles.messageContainer}>
            <Text style={styles.permissionText}>
              {strings("mapa.sem_permissao")}
            </Text>
          </View>
        )}
      </View>
    );
  }
}

```

The location object I'm getting is an array of objects like this:  
{location:
{requestId: 554, latitude: -16.6650444089994, longitude: -49.233523359375}}

I'm kinda lost here. Any help is appreciated.

**Comment by 39otrebla** [comment] 2018-06-09 11:33
If you location object is 
```javascript
```

**Comment by ttencate** [comment] 2018-06-09 12:48
@39otrebla I think @otaviogaiao is having a different issue. My example code does pass `coordinate` correctly, as far as I can tell. Could you please reopen this?

**Comment by djpetenice** [comment] 2018-06-10 08:44
Why was this closed? This issue isn't passing coordinates to the marker it's the rendering issues with clusters and custom markers.

**Comment by lpikora** [comment] 2018-06-11 00:59
I think described issue can be caused by this here https://github.com/novalabio/react-native-maps-super-cluster/issues/38

**Comment by ttencate** [comment] 2018-06-12 15:16
Yes, that seems very likely! I'll do some more testing tonight.

**Comment by ttencate** [comment] 2018-06-12 17:40
Confirmed! Let's continue the discussion on #38 because it contains the best information.

**Comment by psuslick** [comment] 2018-06-18 14:30
On iOS it appears that custom markers will not render after clustering. However, if you are to idle on a location that should display the markers for a period of time (5 minutes for example) the icons will then appear.

I have implemented the zoom level adjustment mentioned in #38 but the icons still will not render correctly.

**Comment by djpetenice** [comment] 2018-06-21 15:30
Yep I've implemented that too #38 hasn't made any difference.

**Comment by DanGDroid** [comment] 2018-07-09 13:04
found this [issue](https://github.com/react-community/react-native-maps/issues/1870#issuecomment-370601097) relevant and solved my problem

**Comment by ttencate** [comment] 2018-07-09 13:53
@DanGDroid That's likely a different problem. I'm not using images inside markers.

I did spot https://github.com/react-community/react-native-maps/issues/578 though, which is about custom markers randomly disappearing in react-native-maps in general (without SuperCluster). So it's possible we are barking up the wrong tree here.

**Comment by DanGDroid** [comment] 2018-07-09 14:54
@ttencate 
i also think it is a `react-native-maps` issue

**Comment by leolusoli** [comment] 2018-07-18 11:37
@DanGDroid @ttencate since the issue is closely linked to [react-community/react-native-maps#578](url), i'll close for redirect the discussion to the right place.

**Closed by leolusoli** 2018-07-18 11:37 UTC
Labels: duplicate

**Comment by tomtom94** [comment] 2018-11-18 07:54
Hello guys, the slowness issue isn't anymore an issue for me hihi !!!! 

Well it is easy, just don't use the props onRegionChange 

```
              // onRegionChange={currentRegion => {
              //   this.onRegionChange(currentRegion);
              // }}
```

This is what causes the android google map slowness issue

Instead you can just simply use the props onRegionChangeComplete

```
              onRegionChangeComplete={currentRegion => {
                this.onRegionChangeComplete(currentRegion);
              }}
```

Cheers. !!

**Comment by abdullah2011-gif** [comment] 2020-12-02 14:31
Each marker need to have a unique key prop. In my case this was causing markers to disappear on random zoom levels.
`<Marker key={key} coordinate={{...marker}}>`

Its working fine on 50+ markers.
