### ISSUE TITLE
Pins not rendering

### ISSUE THREAD

**Issue by minotaurrr** [novalabio/react-native-maps-super-cluster#27] opened 2018-03-12 11:24 UTC
Hey guys,

My clusters are rendering okay but when I zoom in I can't see the pins. Even when I zoom in to the point where I can't anymore, the cluster still says (2) but not actually showing the pins.

Sometimes the cluster will disappear when I click on it, but no pins.

###Environment
```
  "dependencies": {
    "expo": "^25.0.0",
    "react": "16.2.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz",
    "react-native-maps": "^0.20.1",
    "react-native-maps-super-cluster": "^1.3.2"
  }
```

Here's how I'm rendering:
```
<ClusteredMapView 
style={ { flex: 1 } } 
data={ this.state.data } 
textStyle={ { color: '#65bc46' } } 
renderMarker={ this.renderMarker }
preserveClusterPressBehavior={ true } 
edgePadding={ { top: 32, left: 10, right: 64, bottom: 64 } }
initialRegion={ this.state.region } />
```

and here's how the renderMarker function
```
renderMarker = (p) => {
        this.isInBoudingBox({
            latitude: p.location.latitude,
            longitude: p.location.longitude
        }) ?
            <MapMarker key={ p.st_marker_id } bayID={ p.bay_id } tracksViewChanges={ !this.state.initialised } coordinate={ p.location } />
            : null;
    }
```

and this is the MapMarker class
```
render() {
        return (
            <MapView.Marker onPress={e => {e.stopPropagation(); this.onMarkerPress(this.props.bayID)}} coordinate={ this.props.coordinate } tracksViewChanges={this.state.tracksViewChanges}>
                <MapView.Callout tooltip={true} style={[{ flex: -1, position: 'absolute', backgroundColor: 'white', zIndex: 2 }, this.state.isLoaded && { flex: -1, position: 'absolute', width: 220 }]}>
                    {this.state.isLoaded ? 
                    <View>
                        <Text>{this.state.descriptions.description1}</Text>
                        <Text>{this.state.descriptions.description2}</Text>
                        {this.state.descriptions.description3 ? <Text>{this.state.descriptions.description3}</Text> : null}
                    </View>
                    : 
                    <ActivityIndicator size="large" />
                    }
                    
                </MapView.Callout>
            </MapView.Marker>
        )
    }
```

![giphy](https://user-images.githubusercontent.com/28755951/37282730-9b3224be-2649-11e8-84f6-437f7e5ec1c3.gif)

**Comment by 39otrebla** [comment] 2018-03-19 22:18
Did you try playing with `radius` prop? Check [docs](https://github.com/novalabio/react-native-maps-super-cluster#props) for more information. Keep in mind that, anyway, this might happen if markers are really close to each other. Closing for now.

**Closed by 39otrebla** 2018-03-19 22:18 UTC

**Comment by parav01d** [comment] 2019-02-14 11:18
@minotaurrr I have the same problem and I think the problem is "tracksViewChanges={false}" on the Marker-Component. Did you found a way to solve this problem?

**Comment by RWOverdijk** [comment] 2019-03-06 14:25
@parav01d It is. Try using the `icon` prop on custom markers. They don't require tracksViewChanges and they use the native icon, making it a lot faster.
